import Head from "next/head";
import Image from "next/image";
import Script from "next/script";

import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";

const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  return (
    <>
      <Head>
        <title>Hunting Coder</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="next js app, coding hunter" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={`${styles.main} ${inter.className}`}>
        <h1 className={styles.titles}>
          Welcome to <span className="mySpan">Hunting Coder</span>
        </h1>
        <Image
          alt="coder"
          className={styles.myImg}
          src="/homing.jpg"
          width={300}
          height={211}
        />
        <p className={styles.desc}>
          A blog for hunting coders by a hunting coder Lorem ipsum dolor sit
          amet consectetur adipisicing elit. Error sequi officiis, sint,
          expedita non doloremque velit repellendus nam deleniti veniam nobis
          magni animi laudantium dolor, facere dolorem eum totam praesentium.
        </p>
        <div>
          <h2>Latest Blogs</h2>
          <ul>
            <li>
              <div>
                <h3>How to learn Javascript in 2024</h3>
                <p>Javascript is a popular programming language...</p>
                <button className={styles.btn}>Read More</button>
              </div>
            </li>
            <li>
              <div>
                <h3>How to learn Python in 2024</h3>
                <p>Python is a popular programming language...</p>
                <button className={styles.btn}>Read More</button>
              </div>
            </li>
            <li>
              <div>
                <h3>How to learn reactjs in 2024</h3>
                <p>react is a popular programming language...</p>
                <button className={styles.btn}>Read More</button>
              </div>
            </li>
            <li>
              <div>
                <h3>How to learn C++ in 2024</h3>
                <p>C++ is a popular programming language...</p>
                <button className={styles.btn}>Read More</button>
              </div>
            </li>
          </ul>
        </div>
      </main>
    </>
  );
}
